apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: chennai
  namespace: flux-system
spec:
  interval: 5s
  path: ./app/bangalore
  prune: true
  timeout: 3m0s
  sourceRef:
    kind: GitRepository
    name: flux-system 
